name: Setup iOS
description: setup for iOS action.

inputs:
  googleServiceInfoPlistBase64-staging:
    description: base64 encoded GoogleServiceInfo.plist for staging.
    required: true
  googleServiceInfoPlistBase64-production:
    description: base64 encoded GoogleServiceInfo.plist for production.
    required: true

runs:
  using: composite
  steps:
    - name: Put GoogleService-Info.plist for staging
      run: echo ${{ inputs.googleServiceInfoPlistBase64-staging }} > base64 -d ios/Runner/GoogleService-Info-Staging.plist
      shell: bash
    - name: Put GoogleService-Info.plist for production
      run: echo ${{ inputs.googleServiceInfoPlistBase64-production }} > base64 -d ios/Runner/GoogleService-Info-Production.plist
      shell: bash
