name: Setup iOS
description: setup for iOS action.

inputs:
  google_service_info_plist_base64__staging:
    description: base64 encoded GoogleServiceInfo.plist for staging.
    required: true
  google_service_info_plist_base64__production:
    description: base64 encoded GoogleServiceInfo.plist for production.
    required: true

runs:
  using: composite
  steps:
    - name: Put GoogleService-Info.plist for staging
      run: echo GOOGLE_SERVICE_INFO_PLIST > base64 -d ios/Runner/GoogleService-Info-Staging.plist
      shell: bash
      env:
        GOOGLE_SERVICE_INFO_PLIST: ${{ inputs.google_service_info_plist_base64__staging }}
    - name: Put GoogleService-Info.plist for production
      run: echo GOOGLE_SERVICE_INFO_PLIST > base64 -d ios/Runner/GoogleService-Info-Production.plist
      shell: bash
      env:
        GOOGLE_SERVICE_INFO_PLIST: ${{ inputs.google_service_info_plist_base64__production }}
