name: Setup iOS
description: setup for iOS action.

inputs:
  appleApiAuthkeyP8Base64:
    description: base64 encoded AppStoreConnectAPI AuthKey
    required: true
  googleServiceInfoPlistBase64:
    description: base64 encoded GoogleServiceInfo.plist.
    required: true
  firebaseAppIdJsonBase64:
    description: base64 encoded firebase_app_id_file.json
    required: true

runs:
  using: composite
  steps:
    - name: mkdir private_keys
      shell: bash
      run: mkdir private_keys
    - name: Put AuthKey.p8
      shell: bash
      run: echo ${{ inputs.appleApiAuthkeyP8Base64 }} | base64 -d > ios/AuthKey.p8
    - name: Put GoogleService-Info.plist
      shell: bash
      run: echo ${{ inputs.googleServiceInfoPlistBase64 }} | base64 -d > ios/Runner/GoogleService-Info.plist
    - name: Put firebase_app_id_file.json
      shell: bash
      run: echo ${{ inputs.firebaseAppIdJsonBase64 }} | base64 -d > ios/firebase_app_id_file.json
