name: Setup iOS
description: setup for iOS action.

inputs:
  appleApiKeyId:
    description: AppStoreConnectAPI AuthKey Id
    required: true
  appleApiAuthkeyP8Base64:
    description: base64 encoded AppStoreConnectAPI AuthKey
    required: true
  googleServiceInfoPlistBase64:
    description: base64 encoded GoogleServiceInfo.plist.
    required: true

runs:
  using: composite
  steps:
    - name: mkdir private_keys
      run: mkdir private_keys
      shell: bash
    - name: Put AuthKey.p8
      run: echo ${{ inputs.appleApiAuthkeyP8Base64 }} | base64 -d > private_keys/AuthKey_${{ inputs.appleApiKeyId }}.p8
      shell: bash
    - name: Put GoogleService-Info.plist
      run: echo ${{ inputs.googleServiceInfoPlistBase64 }} | base64 -d > ios/Runner/GoogleService-Info.plist
      shell: bash
