name: Build IPA
description: build for ipa.

inputs:
  appleExportOptionsPlistBase64:
    description: base64 encoded ExportOptions.plist
    required: true
  appleApiIssuerId:
    description: AppStoreConnect API Issuer ID
    required: true
  appleApiKeyId:
    description: AppStoreConnect API Key ID
    required: true

outputs:
  ipaPath:
    description: IPA path.
    value: ${{ steps.output-ipa.outputs.ipaPath }}

runs:
  using: composite
  steps:
    - name: Put ExportOptions.plist
      run: echo ${{ inputs.appleExportOptionsPlistBase64 }} | base64 -d > ios/ExportOptions.plist
      shell: bash
    - name: Build
      run: flutter build ios --dart-define-from-file=dart_define.json --no-codesign
      shell: bash
    - name: Archive by xcodebuild
      run: xcodebuild archive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -workspace ./ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath ./build/ios/Runner.xcarchive
      shell: bash
    - name: Export by xcodebuild
      run: xcodebuild -exportArchive -archivePath ./build/ios/Runner.xcarchive -exportPath ./build/ios/ipa -exportOptionsPlist ./ios/ExportOptions.plist -allowProvisioningUpdates -authenticationKeyIssuerID ${{ inputs.APPLE_API_ISSUER_ID }} -authenticationKeyID ${{ inputs.APPLE_API_KEY_ID }} -authenticationKeyPath ./private_keys/AuthKey_${{ inputs.APPLE_API_KEY_ID }}.p8
      shell: bash
    - name: Output IPA
      id: output-ipa
      run: echo "ipaPath=$(echo ./build/ios/ipa/cueue.ipa)" >> $GITHUB_OUTPUT
      shell: bash
