include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"

linter:
  rules:
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    one_member_abstracts: false
    always_put_control_body_on_new_line: false
