name: Setup Android

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
    - name: Put google-services.json for staging
      run: echo GOOGLE_SERVICES_JSON__STAGING >> android/app/src/staging/google-services.json
      env:
        GOOGLE_SERVICES_JSON__STAGING: ${{ secrets.GOOGLE_SERVICES_JSON__STAGING }}
    - name: Put google-services.json for production
      run: echo GOOGLE_SERVICES_JSON__PRODUCTION >> android/app/src/production/google-services.json
      env:
        GOOGLE_SERVICES_JSON__PRODUCTION: ${{ secrets.GOOGLE_SERVICES_JSON__PRODUCTION }}
