name: Setup Web
description: setup for Web action.

inputs:
  googleServicesJsBase64:
    description: base64 encoded initialize.js.
    required: true

runs:
  using: composite
  steps:
    - name: Put initialize.js
      run: echo ${{ inputs.googleServicesJsBase64 }} | base64 -d > web/initialize.js
      shell: bash
