name: Build Android
description: build for android.

inputs:
  flavor:
    description: flavor argument.
    required: true
  base64Keystore:
    description: base64 encoded signing key.
    required: true
  keystorePassword:
    description: keystore password.
    required: true
  keystoreAlias:
    description: keystore alias.
    required: true
  keyPassword:
    description: keystore alias password.
    required: true

outputs:
  aabPath:
    description: AAB path.
    value: ${{ steps.output-aab.outputs.aabPath }}
  apkPath:
    description: APK path.
    value: ${{ steps.sign.outputs.apkPath }}

runs:
  using: composite
  steps:
    - name: Build
      run: flutter build appbundle --flavor ${{ inputs.flavor }}
      shell: bash
    - name: Output AAB
      id: output-aab
      run: echo "::set-output name=aabPath::$(echo ./build/app/outputs/bundle/${{ inputs.flavor }}Release/app-${{ inputs.flavor }}-release.aab)"
      shell: bash
    - name: Sign
      id: sign
      uses: mukeshsolanki/bundletool-action@v1.0.1
      with:
        aabFile: ./build/app/outputs/bundle/${{ inputs.flavor }}Release/app-${{ inputs.flavor }}-release.aab
        base64Keystore: ${{ inputs.base64Keystore }}
        keystorePassword: ${{ inputs.keystorePassword }}
        keystoreAlias: ${{ inputs.keystoreAlias }}
        keyPassword: ${{ inputs.keyPassword }}
