name: Build APK
description: build for apk.

outputs:
  binaryPath:
    description: APK path.
    value: ${{ steps.output-apk.outputs.path }}
  mappingPath:
    description: mapping.txt path.
    value: ${{ steps.output-mapping.outputs.path }}

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: flutter build apk --dart-define-from-file=dart_define.json
    - name: Output APK
      id: output-apk
      shell: bash
      run: echo "path=./build/app/outputs/apk/release/app-release.apk" >> $GITHUB_OUTPUT
    - name: Output Mapping
      id: output-mapping
      shell: bash
      run: echo "path=./build/app/outputs/mapping/release/mapping.txt" >> $GITHUB_OUTPUT
