name: Build Web
description: build for web.

outputs:
  path:
    description: Path.
    value: ${{ steps.output-path.outputs.path }}

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: flutter build web --dart-define-from-file=dart_define.json
    - name: Output Path
      id: output-path
      shell: bash
      run: echo "path=$(echo ./build/web)" >> $GITHUB_OUTPUT
