# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

desc "Get all provisioning profiles."
lane :get_all_cer do
  match(
    app_identifier: ["com.kazakago.cueue", "com.kazakago.cueue.staging"],
    type: "development",
    readonly: true,
  )
  match(
    app_identifier: ["com.kazakago.cueue", "com.kazakago.cueue.staging"],
    type: "adhoc",
    readonly: true,
  )
  match(
    app_identifier: ["com.kazakago.cueue", "com.kazakago.cueue.staging"],
    type: "appstore",
    readonly: true,
  )
end

desc "Update all provisioning profiles."
lane :update_all_cer do
  match(
    app_identifier: ["com.kazakago.cueue", "com.kazakago.cueue.staging"],
    type: "development",
    force_for_new_devices: true,
  )
  match(
    app_identifier: ["com.kazakago.cueue", "com.kazakago.cueue.staging"],
    type: "adhoc",
    force_for_new_devices: true,
  )
  match(
    app_identifier: ["com.kazakago.cueue", "com.kazakago.cueue.staging"],
    type: "appstore",
  )
end

desc "Update all provisioning profiles with register new device."
lane :update_all_cer_with_register_device do |options|
  if options[:name] && options[:udid]
    register_device(
      name: options[:name],
      udid: options[:udid],
    )
    update_all_cer
  else
    raise "need name:[DEVICE_NAME] udid:[DEVICE_UDID] parameters"
  end
end
