name: Setup Android
description: setup for Android action.

inputs:
  googleServicesJsonBase64:
    description: base64 encoded google-services.json.
    required: true

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - name: Put google-services.json
      run: echo ${{ inputs.googleServicesJsonBase64 }} | base64 -d > android/app/google-services.json
      shell: bash
