name: Setup Android
description: setup for Android action.

inputs:
  googleServicesJsonBase64-staging:
    description: base64 encoded google-services.json for staging.
    required: true
  googleServicesJsonBase64-production:
    description: base64 encoded google-services.json for production.
    required: true

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
        cache: gradle
    - name: Put google-services.json for staging
      run: echo ${{ inputs.googleServicesJsonBase64-staging }} | base64 -d > android/app/src/staging/google-services.json
      shell: bash
    - name: Put google-services.json for production
      run: echo ${{ inputs.googleServicesJsonBase64-production }} | base64 -d > android/app/src/production/google-services.json
      shell: bash
