name: Setup Android
description: setup for Android action.

inputs:
  google_services_json_base64__staging:
    description: base64 encoded google-services.json for staging.
    required: true
  google_services_json_base64__production:
    description: base64 encoded google-services.json for production.
    required: true

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
        cache: gradle
    - name: Put google-services.json for staging
      run: echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/src/staging/google-services.json
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.google_services_json_base64__staging }}
    - name: Put google-services.json for production
      run: echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/src/production/google-services.json
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.google_services_json_base64__production }}
