name: Setup Android
description: setup for Android action.

inputs:
  google_services_json__staging:
    description: google-services.json for staging.
    required: true
  google_services_json__production:
    description: google-services.json for production.
    required: true

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
    - name: Put google-services.json for staging
      run: echo ${{ inputs.google_services_json__staging }} > android/app/src/staging/google-services.json
      shell: bash
    - name: Put google-services.json for production
      run: echo ${{ inputs.google_services_json__production }} > android/app/src/production/google-services.json
      shell: bash
