name: Build AAB
description: build for aab.

outputs:
  binaryPath:
    description: AAB path.
    value: ${{ steps.output-aab.outputs.path }}
  mappingPath:
    description: mapping.txt path.
    value: ${{ steps.output-mapping.outputs.path }}

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: flutter build appbundle --dart-define-from-file=dart_define.json
    - name: Output AAB
      id: output-aab
      shell: bash
      run: echo "path=./build/app/outputs/bundle/release/app-release.aab" >> $GITHUB_OUTPUT
    - name: Output Mapping
      id: output-mapping
      shell: bash
      run: echo "path=./build/app/outputs/mapping/release/mapping.txt" >> $GITHUB_OUTPUT
