name: Setup Common
description: setup for flutter action.

inputs:
  dartDefineJsonBase64:
    description: base64 encoded dart_define.json.
    required: true
  serviceAccountJsonBase64:
    description: Base64 encoded ServiceAccount json.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    - name: Put dart_define.json
      shell: bash
      run: echo ${{ inputs.dartDefineJsonBase64 }} | base64 -d > dart_define.json
    - name: Put Credential file
      shell: bash
      run: |
        echo ${{ inputs.serviceAccountJsonBase64 }} | base64 -d > serviceAccount.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=serviceAccount.json" >> $GITHUB_ENV
