name: Setup Common
description: setup for flutter action.

inputs:
  dartDefineJsonBase64:
    description: base64 encoded dart_define.json.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    - name: Check Flutter version
      run: flutter --version
      shell: bash
    - name: Put dart_define.json
      run: echo ${{ inputs.dartDefineJsonBase64 }} | base64 -d > dart_define.json
      shell: bash
