name: Setup Common
description: setup for flutter action.

inputs:
  apiBaseUrl-staging:
    description: api base url for staging.
    required: true
  apiBaseUrl-production:
    description: api base url for production.
    required: true
  appleClientId-staging:
    description: apple client id for staging.
    required: true
  appleClientId-production:
    description: apple client id for production.
    required: true
  appleCallbackUrl-staging:
    description: apple callback url for staging.
    required: true
  appleCallbackUrl-production:
    description: apple callback url for production.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Create dot env file for staging
      uses: weyheyhey/create-dotenv-action@v1
      with:
        filename: .env.staging
      env:
        ^API_BASE_URL: ${{ inputs.apiBaseUrl-staging }}
        ^APPLE_CLIENT_ID: ${{ inputs.appleClientId-staging }}
        ^APPLE_CALLBACK_URL: ${{ inputs.appleCallbackUrl-staging }}
    - name: Create dot env file for production
      uses: weyheyhey/create-dotenv-action@v1
      with:
        filename: .env.production
      env:
        ^API_BASE_URL: ${{ inputs.apiBaseUrl-production }}
        ^APPLE_CLIENT_ID: ${{ inputs.appleClientId-production }}
        ^APPLE_CALLBACK_URL: ${{ inputs.appleCallbackUrl-production }}
    - name: Pub get
      run: flutter pub get
      shell: bash
