name: Setup Common
description: setup for flutter action.

inputs:
  apiBaseUrl:
    description: api base url.
    required: true
  appleClientId:
    description: apple client id.
    required: true
  appleCallbackUrl:
    description: apple callback url.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Mkdir env folder
      run: mkdir -p assets/env
      shell: bash
    - name: Create dot env file
      uses: weyheyhey/create-dotenv-action@v1
      with:
        filename: assets/env/.env
      env:
        ^API_BASE_URL: ${{ inputs.apiBaseUrl }}
        ^APPLE_CLIENT_ID: ${{ inputs.appleClientId }}
        ^APPLE_CALLBACK_URL: ${{ inputs.appleCallbackUrl }}
