name: Setup Common
description: setup for flutter action.

inputs:
  api_base_url__staging:
    description: api base url for staging.
    required: true
  api_base_url__production:
    description: api base url for production.
    required: true
  apple_client_id__staging:
    description: apple client id for staging.
    required: true
  apple_client_id__production:
    description: apple client id for production.
    required: true
  apple_callback_url__staging:
    description: apple callback url for staging.
    required: true
  apple_callback_url__production:
    description: apple callback url for production.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Create dot env file for staging
      uses: weyheyhey/create-dotenv-action@v1
      with:
        filename: '.env.staging'
      env:
        ^API_BASE_URL: ${{ inputs.api_base_url__staging }}
        ^APPLE_CLIENT_ID: ${{ inputs.apple_client_id__staging }}
        ^APPLE_CALLBACK_URL: ${{ inputs.apple_callback_url__staging }}
    - name: Create dot env file for production
      uses: weyheyhey/create-dotenv-action@v1
      with:
        filename: '.env.production'
      env:
        ^API_BASE_URL: ${{ inputs.api_base_url__production }}
        ^APPLE_CLIENT_ID: ${{ inputs.apple_client_id__production }}
        ^APPLE_CALLBACK_URL: ${{ inputs.apple_callback_url__production }}
    - name: Pub get
      run: flutter pub get
      shell: bash
