name: Deploy Web
description: deploy to firebase hosting.

inputs:
  projectId:
    description: Firebase project ID
    required: true
  siteId:
    description: Firebase hosting site id.
    required: true
  token:
    description: Upload token - see Firebase CLI Reference.
    required: true

runs:
  using: composite
  steps:
    - name: Install Firebase
      run: npm install -g firebase-tools
      shell: bash
    - name: Use project
      run: firebase use --add ${{ inputs.projectId }} --token ${{ inputs.token }}
      shell: bash
    - name: Apply target
      run: firebase target:apply hosting default ${{ inputs.siteId }} --token ${{ inputs.token }}
      shell: bash
    - name: Upload
      run: firebase deploy --only hosting:default --token ${{ inputs.token }}
      shell: bash
