name: Upload to Firebase for Web
description: upload to firebase hosting.

inputs:
  projectId:
    description: Firebase project ID
    required: true
  siteId:
    description: Firebase hosting site id.
    required: true

runs:
  using: composite
  steps:
    - name: Install Firebase
      shell: bash
      run: npm install -g firebase-tools
    - name: Use project
      shell: bash
      run: firebase use --add ${{ inputs.projectId }}
    - name: Apply target
      shell: bash
      run: firebase target:apply hosting default ${{ inputs.siteId }}
    - name: Upload
      shell: bash
      run: firebase deploy --only hosting:default
