import 'package:cueue/api/mapper/content/content_response_mapper.dart';
import 'package:cueue/api/mapper/invitation/invitation_response_mapper.dart';
import 'package:cueue/api/mapper/menu/menu_request_mapper.dart';
import 'package:cueue/api/mapper/menu/menu_response_mapper.dart';
import 'package:cueue/api/mapper/menu/menu_summary_response_mapper.dart';
import 'package:cueue/api/mapper/menu/time_frame_request_mapper.dart';
import 'package:cueue/api/mapper/menu/time_frame_response_mapper.dart';
import 'package:cueue/api/mapper/recipe/recipe_request_mapper.dart';
import 'package:cueue/api/mapper/recipe/recipe_response_mapper.dart';
import 'package:cueue/api/mapper/recipe/recipe_summary_response_mapper.dart';
import 'package:cueue/api/mapper/tag/tag_order_request_mapper.dart';
import 'package:cueue/api/mapper/tag/tag_request_mapper.dart';
import 'package:cueue/api/mapper/tag/tag_response_mapper.dart';
import 'package:cueue/api/mapper/user/user_response_mapper.dart';
import 'package:cueue/api/mapper/user/user_summary_response_mapper.dart';
import 'package:cueue/api/mapper/workspace/workspace_response_mapper.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

final contentResponseMapperProvider = Provider((ref) => const ContentResponseMapper());
final userResponseMapperProvider = Provider((ref) => UserResponseMapper(ref.read(workspaceResponseMapperProvider), ref.read(contentResponseMapperProvider)));
final userSummaryResponseMapperProvider = Provider((ref) => UserSummaryResponseMapper(ref.read(contentResponseMapperProvider)));
final workspaceResponseMapperProvider = Provider((ref) => WorkspaceResponseMapper(ref.read(userSummaryResponseMapperProvider)));
final tagResponseMapperProvider = Provider((ref) => const TagResponseMapper());
final tagRequestMapperProvider = Provider((ref) => const TagRequestMapper());
final recipeResponseMapperProvider = Provider((ref) => RecipeResponseMapper(ref.read(tagResponseMapperProvider), ref.read(contentResponseMapperProvider)));
final recipeSummaryResponseMapperProvider = Provider((ref) => RecipeSummaryResponseMapper(ref.read(contentResponseMapperProvider)));
final recipeRequestMapperProvider = Provider((ref) => const RecipeRequestMapper());
final menuSummaryResponseMapperProvider = Provider((ref) => MenuSummaryResponseMapper(ref.read(timeFrameResponseMapperProvider), ref.read(recipeSummaryResponseMapperProvider)));
final menuResponseMapperProvider = Provider((ref) => MenuResponseMapper(ref.read(timeFrameResponseMapperProvider), ref.read(recipeSummaryResponseMapperProvider)));
final menuRequestMapperProvider = Provider((ref) => MenuRequestMapper(ref.read(timeFrameRequestMapperProvider)));
final timeFrameResponseMapperProvider = Provider((ref) => const TimeFrameResponseMapper());
final timeFrameRequestMapperProvider = Provider((ref) => const TimeFrameRequestMapper());
final tagOrderRequestMapperProvider = Provider((ref) => const TagOrderRequestMapper());
final invitationResponseMapperProvider = Provider((ref) => InvitationResponseMapper(ref.read(workspaceResponseMapperProvider)));
