name: Build iOS
description: build for ios.

inputs:
  flavor:
    description: flavor argument.
    required: true
  exportMethod:
    description: ad-hoc, develop, enterprise or app-store.
    required: true

outputs:
  ipaPath:
    description: IPA path.
    value: ${{ steps.output-ipa.outputs.ipaPath }}

runs:
  using: composite
  steps:
    - name: Build
      run: flutter build ipa --flavor ${{ inputs.flavor }} --export-method ${{ inputs.exportMethod }}
      shell: bash
    - name: Output IPA
      id: output-ipa
      run: echo "::set-output name=ipaPath::$(echo ./build/ios/ipa/cueue.ipa)"
      shell: bash
