name: DeployStaging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common
        uses: ./.github/actions/setup_common
        with:
          apiBaseUrl-staging: ${{ secrets.API_BASE_URL__STAGING }}
          apiBaseUrl-production: ${{ secrets.API_BASE_URL__PRODUCTION }}
          appleClientId-staging: ${{ secrets.APPLE_CLIENT_ID__STAGING }}
          appleClientId-production: ${{ secrets.APPLE_CLIENT_ID__PRODUCTION }}
          appleCallbackUrl-staging: ${{ secrets.APPLE_CALLBACK_URL__STAGING }}
          appleCallbackUrl-production: ${{ secrets.APPLE_CALLBACK_URL__PRODUCTION }}
      - name: Setup Android
        uses: ./.github/actions/setup_android
        with:
          googleServicesJsonBase64-staging: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64__STAGING }}
          googleServicesJsonBase64-production: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64__PRODUCTION }}
      - name: Build
        id: build
        uses: ./.github/actions/build_android
        with:
          flavor: staging
          dotEnvFile: .env.staging
          base64Keystore: ${{ secrets.ANDROID_SIGNING_KEY__BASE64 }}
          keystorePassword: ${{ secrets.ANDROID_SIGNING_KEY__PASSWORD }}
          keystoreAlias: ${{ secrets.ANDROID_SIGNING_KEY__ALIAS }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY__ALIAS_PASSWORD }}
      - name: Deploy
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID__STAGING }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: ${{ secrets.FIREBASE_APP_DISTRIBUTION_TESTER_GROUP }}
          file: ${{ steps.build.outputs.apkPath }}
