name: DeployStaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common
        uses: ./.github/actions/setup_common
        with:
          dartDefineJsonBase64: ${{ secrets.DART_DEFINE_JSON_BASE64__STAGING }}
      - name: Setup Android
        uses: ./.github/actions/setup_android
        with:
          keystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64__STAGING }}
          googleServicesJsonBase64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64__STAGING }}
      - name: Build
        id: build
        uses: ./.github/actions/build_apk
      - name: Deploy
        uses: ./.github/actions/deploy_app
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID__STAGING }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: ${{ secrets.FIREBASE_APP_DISTRIBUTION_TESTER_GROUP }}
          file: ${{ steps.build.outputs.apkPath }}
  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common
        uses: ./.github/actions/setup_common
        with:
          dartDefineJsonBase64: ${{ secrets.DART_DEFINE_JSON_BASE64__STAGING }}
      - name: Setup iOS
        uses: ./.github/actions/setup_ios
        with:
          appleApiKeyId: ${{ secrets.APPLE_API_KEY_ID }}
          appleApiAuthkeyP8Base64: ${{ secrets.APPLE_API_AUTHKEY_P8_BASE64 }}
          googleServiceInfoPlistBase64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64__STAGING }}
          firebaseAppIdJsonBase64: ${{ secrets.FIREBASE_APP_ID_FILE_JSON_BASE64__STAGING }}
      - name: Build
        id: build
        uses: ./.github/actions/build_ipa
        with:
          appleExportOptionsPlistBase64: ${{ secrets.APPLE_EXPORT_OPTIONS_PLIST_BASE64__ADHOC }}
          appleApiIssuerId: ${{ secrets.APPLE_API_ISSUER_ID }}
          appleApiKeyId: ${{ secrets.APPLE_API_KEY_ID }}
      - name: Deploy
        uses: ./.github/actions/deploy_app
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_IOS__STAGING }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: ${{ secrets.FIREBASE_APP_DISTRIBUTION_TESTER_GROUP }}
          file: ${{ steps.build.outputs.ipaPath }}
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common
        uses: ./.github/actions/setup_common
        with:
          dartDefineJsonBase64: ${{ secrets.DART_DEFINE_JSON_BASE64__STAGING }}
      - name: Build
        id: build
        uses: ./.github/actions/build_web
      - name: Deploy
        uses: ./.github/actions/deploy_web
        with:
          projectId: ${{ secrets.FIREBASE_PROJECT_ID__STAGING }}
          siteId: ${{ secrets.FIREBASE_HOSTING_SITE_ID__STAGING }}
          token: ${{ secrets.FIREBASE_TOKEN }}
