name: UnitTest

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common
        uses: ./.github/actions/setup_common
        with:
          apiBaseUrl-staging: ${{ secrets.API_BASE_URL__STAGING }}
          apiBaseUrl-production: ${{ secrets.API_BASE_URL__PRODUCTION }}
          appleClientId-staging: ${{ secrets.APPLE_CLIENT_ID__STAGING }}
          appleClientId-production: ${{ secrets.APPLE_CLIENT_ID__PRODUCTION }}
          appleCallbackUrl-staging: ${{ secrets.APPLE_CALLBACK_URL__STAGING }}
          appleCallbackUrl-production: ${{ secrets.APPLE_CALLBACK_URL__PRODUCTION }}
      - name: Test
        uses: ./.github/actions/test
