name: UnitTest

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [setup-common]
    steps:
      - name: Test
        run: flutter test
