name: UnitTest

on:
  push:
    branches: [ main, production ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common
        uses: ./.github/actions/setup_common
        with:
          apiBaseUrl: ${{ secrets.API_BASE_URL__STAGING }}
          appleClientId: ${{ secrets.APPLE_CLIENT_ID__STAGING }}
          appleCallbackUrl: ${{ secrets.APPLE_CALLBACK_URL__STAGING }}
      - name: Test
        uses: ./.github/actions/test
