name: UnitTest

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common
        uses: ./.github/actions/setup_common
      - name: Test
        uses: ./.github/actions/test
