name: UnitTest

on:
  push:
    branches:
      - main
      - production
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Common
        uses: ./.github/actions/setup_common
        with:
          dartDefineJsonBase64: ${{ secrets.DART_DEFINE_JSON_BASE64 }}
          serviceAccountJsonBase64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}
      - name: Test
        uses: ./.github/actions/test
