name: UnitTest

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Create staging dot env file
      uses: microsoft/variable-substitution@v1
      with:
        files: '.env.staging'
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL__STAGING }}
        APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID__STAGING }}
        APPLE_CALLBACK_URL: ${{ secrets.APPLE_CALLBACK_URL__STAGING }}
    - name: Create production dot env file
      uses: microsoft/variable-substitution@v1
      with:
        files: '.env.production'
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL__PRODUCTION }}
        APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID__PRODUCTION }}
        APPLE_CALLBACK_URL: ${{ secrets.APPLE_CALLBACK_URL__PRODUCTION }}
    - name: Pub get
      run: flutter pub get
    - name: Test
      run: flutter test
