name: UnitTest

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Create staging dot env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_API_BASE_URL: ${{ secrets.API_BASE_URL__STAGING }}
        envkey_APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID__STAGING }}
        envkey_APPLE_CALLBACK_URL: ${{ secrets.APPLE_CALLBACK_URL__STAGING }}
        file_name: .env.staging
        fail_on_empty: true
    - name: Create production dot env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_API_BASE_URL: ${{ secrets.API_BASE_URL__PRODUCTION }}
        envkey_APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID__PRODUCTION }}
        envkey_APPLE_CALLBACK_URL: ${{ secrets.APPLE_CALLBACK_URL__PRODUCTION }}
        file_name: .env.production
        fail_on_empty: true
    - name: Pub get
      run: flutter pub get
    - name: Test
      run: flutter test
